In [3]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB


In [4]:
data = pd.read_csv("web_scraping/allegro_scraped1.csv", sep=',', names = ['Sentiment', 'Opinion'],  encoding= 'utf-8')
df = pd.DataFrame(data)
# shows top 10 rows
df.head(10)

Sentiment                                            Opinion
0          1                     oszusci i zlodzieje wielki syf
1          1  allegro to oszuści i złodzieje , nie zwracają ...
2          1  Wystawiłem parę rzeczy prywatnych w niedrogich...
3          1  Zlodzieje i oszusci. Powymyslali prowizje. Zam...
4          1  Witam, wystawiłem przedmiot na allegro w sierp...
5          1  Niestety firma dba tylko o kasę i wspiera prze...
6          1  Serwis Allegro oficjalnie w swoim stanowisku s...
7          1  Suport allegro to są kompletne ameby umysłowe....
8          1  Obsługa działa na niekorzyść sprzedającego. Ku...
9          1  Kochani Sprzedający na Allegro !!!  Zajrzałem ...

### How many cells with positive sentiment?

In [5]:
print(len(df[df.Sentiment == 1]))
print(len(df[df.Sentiment == 5]))

429
326


In [6]:
df.loc[df['Sentiment'] == 1, 'Sentiment']=0
df.loc[df['Sentiment'] == 5, 'Sentiment']=1

In [7]:
df.head()

Sentiment                                            Opinion
0          0                     oszusci i zlodzieje wielki syf
1          0  allegro to oszuści i złodzieje , nie zwracają ...
2          0  Wystawiłem parę rzeczy prywatnych w niedrogich...
3          0  Zlodzieje i oszusci. Powymyslali prowizje. Zam...
4          0  Witam, wystawiłem przedmiot na allegro w sierp...

In [8]:
df_x =df['Opinion']
df_y = df['Sentiment']

In [9]:
df_x

0                         oszusci i zlodzieje wielki syf
1      allegro to oszuści i złodzieje , nie zwracają ...
2      Wystawiłem parę rzeczy prywatnych w niedrogich...
3      Zlodzieje i oszusci. Powymyslali prowizje. Zam...
4      Witam, wystawiłem przedmiot na allegro w sierp...
                             ...                        
778                                              Polecam
779    Polecam szybka transakcja, możliwość dużych ra...
780    wysyłaliśmy wiele emaili i nikt nie odpowiedzi...
781                                                Super
782    Jestem mega niezadowolona, sklep najpierw wysł...
Name: Opinion, Length: 783, dtype: object

In [10]:
vectorizer = CountVectorizer()

In [11]:
# print(vectorizer.get_feature_names()[900:1000])

In [12]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size = 0.25, random_state = 4)

In [13]:
x_train_countvectorizer = vectorizer.fit_transform(x_train)

In [14]:
print(x_train[1])
print(x_train_countvectorizer[1])

allegro to oszuści i złodzieje , nie zwracają prowizji , kłamią i okradają ludzi , Francois Nuyts prezes to złodziej który przypałętał się aby okradać Polaków , powinni go zgnoić ,ten śmieć w swoim kraju był sądzony za pedofilję , to była głośna sprawa , kasa go uratowała , na szczęście amazon jest blisko im allegro nie da rady
  (0, 3130)	1


In [15]:
mnb = MultinomialNB()

In [16]:
mnb.fit(x_train_countvectorizer, y_train) 

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [17]:
x_test_countvectorizer = vectorizer.transform(x_test)

In [18]:
print(mnb.score(x_test_countvectorizer, y_test))

0.8622448979591837


In [30]:
# Grid Search




In [19]:
pred = mnb.predict(x_test_countvectorizer)

In [20]:
pred

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
      dtype=int64)

In [21]:
rezult = np.array(y_test)

In [22]:
rezult

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 3, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 2, 1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 0, 4, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2],
      dtype=int64)

In [23]:
count = 0

In [24]:
for i in range(len(pred)):
    if pred[i] == rezult[i]:
        count += 1    

In [25]:
count

169

In [26]:
len(pred)

196

In [27]:
accuracy = count/len(pred)

In [28]:
accuracy

0.8622448979591837

### The evaluation of coments typed by the user.

In [29]:
test_set = ['zdecydowanie nie polecam tego gównianego sklepu']  

new_test = vectorizer.transform(test_set) 

mnb.predict(new_test) # model przewiduje, czy wpisane zdanie jest positive=1, czy negative=0

array([0], dtype=int64)