In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB


In [10]:
data = pd.read_csv("web_scraping/allegro_scraped.csv", sep=',', names = ['Sentiment', 'Opinion'],  encoding= 'unicode_escape')
df = pd.DataFrame(data)
# shows top 10 rows
df.head(10)

Sentiment                                            Opinion
0          1  Zlodzieje i oszusci. Powymyslali prowizje. Zam...
1          1  allegro to oszuœci i z³odzieje , nie zwracaj¹ ...
2          1  Witam, wystawi³em przedmiot na allegro w sierp...
3          1  Niestety firma dba tylko o kasê i wspiera prze...
4          1  Serwis Allegro oficjalnie w swoim stanowisku s...
5          1  Suport allegro to s¹ kompletne ameby umys³owe....
6          1  Obs³uga dzia³a na niekorzyœæ sprzedaj¹cego. Ku...
7          1  Kochani Sprzedaj¹cy na Allegro !!!  Zajrza³em ...
8          1  Jedna negatywna opinia klienta spowoduje, ¿e w...
9          1  Sprzeda³em przedmiot za który kupuj¹cy nie zap...

### How many cells with positive sentiment?

In [12]:
print(len(df[df.Sentiment == 1]))
print(len(df[df.Sentiment == 5]))

429
320


In [14]:
df.loc[df['Sentiment'] == 1, 'Sentiment']=0
df.loc[df['Sentiment'] == 5, 'Sentiment']=1

In [15]:
df.head()

Sentiment                                            Opinion
0          0  Zlodzieje i oszusci. Powymyslali prowizje. Zam...
1          0  allegro to oszuœci i z³odzieje , nie zwracaj¹ ...
2          0  Witam, wystawi³em przedmiot na allegro w sierp...
3          0  Niestety firma dba tylko o kasê i wspiera prze...
4          0  Serwis Allegro oficjalnie w swoim stanowisku s...

In [16]:
df_x =df['Opinion']
df_y = df['Sentiment']

In [17]:
df_x

0      Zlodzieje i oszusci. Powymyslali prowizje. Zam...
1      allegro to oszuœci i z³odzieje , nie zwracaj¹ ...
2      Witam, wystawi³em przedmiot na allegro w sierp...
3      Niestety firma dba tylko o kasê i wspiera prze...
4      Serwis Allegro oficjalnie w swoim stanowisku s...
                             ...                        
772                                         Wszystko  ok
773                     Szybko i profesjonalnie, polecam
774    Tragedia, dno, ¿enada, otrzyma³em tv niefabryc...
775                     Sprawnie, profesjonslnie, super.
776    Czas dostawy i towar ok. Trochê rozczarowuj¹cy...
Name: Opinion, Length: 777, dtype: object

In [18]:
vectorizer = CountVectorizer()

In [19]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size = 0.25, random_state = 4)

In [20]:
x_train_countvectorizer = vectorizer.fit_transform(x_train)

In [21]:
print(x_train[0])
print(x_train_countvectorizer[0])

Zlodzieje i oszusci. Powymyslali prowizje. Zamykam konto i baybay allegro.
  (0, 1612)	1
  (0, 2485)	1
  (0, 478)	1
  (0, 791)	1
  (0, 98)	1
  (0, 3457)	1
  (0, 6250)	1
  (0, 6896)	1
  (0, 6516)	2
  (0, 6311)	1
  (0, 281)	1
  (0, 443)	1
  (0, 3604)	1
  (0, 3969)	1
  (0, 1672)	1
  (0, 4570)	1
  (0, 3052)	1
  (0, 5397)	1
  (0, 3364)	1
  (0, 5435)	1
  (0, 2694)	1
  (0, 4873)	1
  (0, 5370)	1
  (0, 2742)	1
  (0, 4662)	1
  (0, 1124)	1
  (0, 6113)	1
  (0, 4347)	1
  (0, 5111)	1
  (0, 3524)	1


In [22]:
mnb = MultinomialNB()

In [23]:
mnb.fit(x_train_countvectorizer, y_train) 

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [24]:
x_test_countvectorizer = vectorizer.transform(x_test)

In [25]:
pred = mnb.predict(x_test_countvectorizer)

In [26]:
pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0],
      dtype=int64)

In [27]:
rezult = np.array(y_test)

In [28]:
rezult

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 2, 0, 1, 1, 4, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 1, 1, 1, 3, 1, 0, 0,
       0, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 1, 1, 1],
      dtype=int64)

In [29]:
count = 0

In [30]:
for i in range(len(pred)):
    if pred[i] == rezult[i]:
        count += 1    

In [31]:
count

172

In [32]:
len(pred)

195

In [33]:
accuracy = count/len(pred)

In [34]:
accuracy

0.882051282051282

### The evaluation of coments typed by the user.

In [35]:
test_set = ['zdecydowanie nie polecam tego gównianego sklepu']  

new_test = vectorizer.transform(test_set) 

mnb.predict(new_test) # model przewiduje, czy wpisane zdanie jest positive=1, czy negative=0

array([0], dtype=int64)